### ISSUE TITLE
DND sometimes shows as "on a call"

### ISSUE THREAD

**Issue by dandrzejewski** [chan-sccp/chan-sccp#324] opened 2016-08-14 23:16 UTC
When I reboot the PBX or reload the module, a phone that is on DND will sometimes show on other phones as "on the phone" rather than DND.

**Reproduction Steps:**
# Set DND on a phone
# Restart the pbx or reload the module

**Expected behavior:**

Phone should show up on other phones hints as DND every single time.

**Observed behavior:**

Phone will sometimes show as "on the phone" instead.

**Screenshots**

![screenshot 1 copy](https://cloud.githubusercontent.com/assets/181952/17652749/571ff92e-6253-11e6-803e-2963f41529da.png)

This is how it shows when it's doing the wrong thing.

**chan-sccp version:** 
Version is current develop branch as of today:
Skinny Client Control Protocol (SCCP). Release: 4.3.0 develop - 575aa22M (built by 'root' on '2016-08-14 22:36:39 UTC')

**asterisk version:** 
13.7.2

**Addition / Optional Information:**

I can attach logs if needed, but I don't have any kind of debugging enabled currently. Please let me know if you need them.

This did happen on a previous development revision from a few months ago (unfortunately I don't still have that around to know the exact revision).

**Comment by dkgroot** [comment] 2016-12-10 15:39
Cause analysis:

We were trying to save a couple of CPU cycles by checking if a hint is observed or not, if there are not registered 'Watchers', we did not see a need to send an update for the DND change event to asterisk. Which in retrospect is an error on our part.

While dialing (app_dial) will ask us about the Line/Channel status and it being DND and we return Busy. Wenn we return this status, asterisk is trying to be overyly helpfull and updates the hint for us :-( 

Now FreePBX twists things a little bit around, and checks the hint status before dialing. (FYI: Dialplan checks against hints are not counted as a watcher, so the update of the DND status never changed the state from Busy back to Idle). We are not updating the hint, because we never set it (app_dial did that for us), so we are not expecting it to change.

So there are multiple assumptions which cause this loop:
- chan-sccp: unwatched hints don't need updating.
- app_dial: updates this hint for us, by asking us the current state for this call.
- freepbx: assumes the hint is correct and uses it, without trying to dial.

Possible fixes:
- updating hints regardless of them being watched (general fix for all hints and all events). Needs carefull consideration, coding and testing.
- when changing dnd state, force reset hint (very specific for this event only). Simple solution, but might not catch everything.

**Comment by dkgroot** [comment] 2016-12-10 22:31
Initial solution for this issue: Update PBX Hint when we do not have any subscribers or the hint was not processed via shortcut method in all instances.

@dandrzejewski Please run:
git checkout issues/324

And check if this solves the issue.

@marcelloceschia : Can you verify ?

**Comment by ErmakovDmitriy** [comment] 2016-12-11 07:33
Thank You!
I checked branch issues/324.

With Your fix (as I can see without long testing), all works as expected.
Here is DND switch logs.
I checked calls with this algorithm:
1) Set DND=off, make inbound (to line 8649 - SCCP phone) call - all correct, normal call
2) Set DND=silent, make inbound call - all correct, silent call (core show hint 8649 "SCCP/8649&Custom:DND  State:Idle")
3) Set DND=reject, make inbound call - status busy, call rejected (core show hint 8649 "SCCP/8649&Custom:DND  State:Busy")
4) Set DND=off (completing the DND cycle) - all correct, normal call (core show hint 8649 "SCCP/8649&Custom:DND  State:Idle").

In attachement You can see DND switch log from my asterisk.

[issues_324_DND_switch.txt](https://github.com/chan-sccp/chan-sccp/files/644303/issues_324_DND_switch.txt)

**Comment by dkgroot** [comment] 2016-12-11 14:33
Hi Dmitriy,

Thanks for testing this.

Did you notice any negative side effects during other call behaviour like transfer, shared line, call pickup ? If not i would move to merge this into develop.

**Comment by ErmakovDmitriy** [comment] 2016-12-11 15:08
I will check transfer tomorrow.

I have never used shared line, call pickup, so I will read about this functions in wiki and I will try to check them too.

**Comment by dkgroot** [comment] 2016-12-11 15:14
Ok :-) Have fun experimenting with them. You might like shared line, it's the original reason for chan-sccp's existence.
At the moment i am trying to make sure we do not check in faulty patches and fixes, so testing before merging patches is the way to go.

**Comment by ErmakovDmitriy** [comment] 2016-12-12 07:15
Hello!
I saw today: When I do 'sccp reset SEPXXXXXXXXXXXX' I have segmentation fault error:

`/usr/sbin/safe_asterisk: line 163: 52694 Segmentation fault      (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/${TTY} 2>&1 < /dev/${TTY}`

I have tested shared line - Ok.
I have not tested call pickup yet.

I have core dump file and I can attach it here or send by email.
The file are big: about 200Mb.

Can I help with debugging?

**Comment by dkgroot** [comment] 2016-12-12 14:04
Can you easilty reproduce the segfault by running reset again, or was it just this once. BTW: most of the time you will want to use restart not reset, which is a lot faster.

Sending a coredump file does not work. You need to create a so called backtrace from it, see:
https://github.com/chan-sccp/chan-sccp/wiki/Reporting%20Bugs

You are using safe_asterisk so you could use our replacement version in contrib/safe_asterisk + contrib/safe_asterisk_backtrace which will generate a backtrace automatically when a segfault happens. The backtrace result will be mailed to the 'NOTIFY' e-mail address you specify. That might be easier in the future.

**Comment by dkgroot** [comment] 2016-12-12 17:16
@ErmakovDmitriy & @dandrzejewski 
Please pull the latest changes of the issues/324 branch and retest. Two small changes where committed too them, that might change the outcome slightly.

**Comment by ErmakovDmitriy** [comment] 2016-12-17 09:48
Hello!
I am sorry, I was busy all week.
Today I tested Your latest branch changes and I did not see any errors.
I will try to try this branch in production on Monday or Tuesday.

Thank You!

**Closed** 2016-12-27 10:06 UTC
Labels: branch_development, bug, hint, in progress, prio 3, waiting_for_reply
