### ISSUE TITLE
Asterisk CLI hangs while sccp reload

### ISSUE THREAD

**Issue by jozzus** [chan-sccp/chan-sccp#338] opened 2016-10-18 08:19 UTC
[Short description of problem here]
When HotLine funcionality is enabled(hotline_enabled=no) changing configuration of Autho registred device couses hangign Asterisk cli
**Reproduction Steps:**
1. Enable hotline_enabled=no 
2. Bootup device not yet registred
3. Check  that device is registred (sccp show devices) 
4. Create config for device and line in sccp.conf
5. sccp reload

**Expected behavior:**
Configuration must be applied and device rebooted with new configuration.

**Observed behavior:**

Asterisk cli after half a minute has hangs

**Screenshots**

localhost*CLI> sccp show devices

+--- Devices --------------------------------------------------------------------------------------------------------------------------------------------+
| Descr                     Address                                      Mac              RegState   Token RegTime                   Act Lines Nat       |
- ========================= ============================================ ================ ========== ===== ========================= === ===== ========= +
  | 77212                                                               -- SEP001B5434F07C  None       No To  Wed Dec 31 19:00:00 1969  No 0          Auto |
  | <not set>                                           10.1.6.34:15874 SEP0017E0B28967  OK         No To  Tue Oct 18 03:53:09 2016  No 1     (Auto)Off |
  +--------------------------------------------------------------------------------------------------------------------------------------------------------+
  localhost_CLI> sccp reload
  SCCP reloading configuration. 0x7fdb7c000c00
  localhost_CLI>

**chan-sccp version:** (include revision if relevant)
Skinny Client Control Protocol (SCCP). Release: 4.3.0 TRUNK - 7a9996bM (built by 'root' on '2016-10-18 06:31:40 UTC')

**asterisk version:** (include revision if relevant)
Asterisk 13.11.2 built by root @ localhost.localdomain on a x86_64 running Linux on 2016-10-05 09:34:47 UTC

 Problem can be reliably reproduced, doesn't happen randomly: Yes
- Platform:
  - [CPU]
  - [64 Bit]
    *centos 7

**Comment by dkgroot** [comment] 2016-11-19 12:41
@jozzus 
I just ran a couple of tests with the development branch and cannot reproduce this. 

If i set hotline_enable=no, a device without an entry in sccp.conf is not allowed to connect and refused (as expected). When i then add the device and issue a reload, the device is added and allowed to register.
If i set hotline_enable=yes, a device without an entry in sccp.conf is allowed to connect and gets a hotline assigned. When i then add the device and issue a reload, the device is added and allowed to register.
So in the development branch this seems to be working correctly as far as i can tell. Development branch will be merged into master once all the major bugs in the current issue list have been dealt with.

**Closed by dkgroot** 2016-11-19 12:41 UTC
Labels: regression, reload
