### ISSUE TITLE
Device Restarts upon receiving a faulty 'CallInfoDynamic' message

### ISSUE THREAD

**Issue by abradfordcms** [chan-sccp/chan-sccp#357] opened 2016-12-14 23:04 UTC
Device Restarts upon receiving a faulty 'CallInfoDynamic' message
Phone generates IllegalArgumentException and complains about Invalid Call Id=201

**Reproduction Steps:**

1. Asterisk needs to be up for a consistent number of weeks (sometimes a month) for this to occur - at least in the cases exhibited across two environments, so far
2. Place inbound call to phone
3. Upon answering (or sometimes upon call arriving at endpoint) the endpoint will un-register and then cycle into Registering 

**Expected behavior:**

Normal operation - no phone recycles

**Observed behavior:**

Regardless of if the devices lose registration (i.e intermittent network issues, power cycle, etc) prior to the condition being hit - the problem will still occur. End users, when faced with this issue, have tried to power cycle the phone only for it to occur again. Restarting the Asterisk service appears to be the only fix. 

Asterisk:
- version: 11.16.0 
chan-sccp: 
- branch: 4.3.0 develop
- revison: 1e00778
Phone:
- type: 7975
- name: SEP2C3ECF76C81E
- firmware: 9.4(2SR1.1S)

Asterisk Full Log
```
[2016-12-14 08:45:06] VERBOSE[27153][C-00000947] pbx.c:     -- Executing [s@macro-dial-one:43] Dial("SIP/bwcom-1-00001056", "SCCP/102,15,Ttr") in new stack
[2016-12-14 08:45:06] VERBOSE[27153][C-00000947] ast111.c:     -- SCCP: Asterisk request to call SCCP/102-00001F7F (dest:102, timeout: 0)
[2016-12-14 08:45:06] VERBOSE[27153][C-00000947] sccp_pbx.c:     -- 102: Asterisk request to call SCCP/102-00001F7F
[2016-12-14 08:45:06] VERBOSE[27153][C-00000947] sccp_utils.c:  SCCP: packet hex dump:
 00000000 - 5C 00 00 00 00 00 00 00  4A 01 00 00 01 00 00 00  - \.......J.......            # lel_lineInstance = 1
 00000010 - 7F 1F 00 00 01 00 00 00  00 00 00 00 00 00 00 00  - ................            # lel_callReference (ie: callid) = 7F 1F => 8063(dec), lel_callType=1
 00000020 - C9 00 00 00 00 00 00 00  00 00 00 00 39 37 38 38  - ............9788            # lel_callInstance: C9 00 => 201(dec) <-- Questions
 00000030 - 33 35 31 38 32 31 00 00  31 30 32 00 00 00 00 00  - 351821..102.....
 00000040 - 00 00 57 4F 4A 41 53 2C  4A 41 4D 45 53 00 50 61  - ..WOJAS,JAMES.Pa
 00000050 - 74 72 69 63 69 61 20 4D  79 65 72 73 00 00 00 00  - tricia Myers....
 00000060 - 00 00 00 00                                       - ....
[2016-12-14 08:45:06] VERBOSE[27153][C-00000947] app_dial.c:     -- Called SCCP/102
[2016-12-14 08:45:06] VERBOSE[27153][C-00000947] app_dial.c:     -- SCCP/102-00001F7F is ringing
[2016-12-14 08:45:06] VERBOSE[12886] sccp_device.c:  SCCP: Clean Device SEP2C3ECF76C81E
[2016-12-14 08:45:06] VERBOSE[12886] sccp_device.c:   == SCCP: Remove Line 102 from device SEP2C3ECF76C81E
[2016-12-14 08:45:06] VERBOSE[12886] sccp_device.c:   == SCCP: Unregister Device SEP2C3ECF76C81E
[2016-12-14 08:45:06] VERBOSE[24574] sccp_devstate.c:     -- SEP2C3ECF76C81E: (sccp_devstate_deviceRegisterListener) device unregistered
[2016-12-14 08:45:21] VERBOSE[27153][C-00000947] app_dial.c:     -- Nobody picked up in 15000 ms
```

Questions:
1. How can the call instance be this high ? It's defined as:
uint8_t callInstance = refLine->statistic.numberOfActiveChannels + refLine->statistic.numberOfHeldChannels + 1;

2. CallInfoDynamic need the callinstance maybe this should have been the callid instead

Phone Log
```
1290: ERR 08:00:00.001132 NTP: Wed Dec 14 08:00:00 2016
1291: DBG 08:22:21.820654 cffs_journal_commit() change journal base 0xb40000
1292: DBG 08:22:21.821991 cffs_journal_create() sec 98
1293: DBG 08:22:21.823222 cffs_journal_commit() new journal base 0xc40000/hdr:4/data:5
1294: DBG 08:22:21.832508 cffs_gc(): runing gc 1
1295: DBG 08:37:21.828649 cffs_gc(): runing gc 1
1296: ERR 08:45:04.010513 JVM: Startup Module Loader|cip.sccp.co:? - SccpConnection caught an exception! : Invalid Call Id=201 - connection closed
1297: ERR 08:45:04.016870 JVM: 8:45:04a|java.lang.IllegalArgumentException: Invalid Call Id=201
	at cip.callagent.cj.a(I)Lcip/callagent/cj;(Unknown Source)
	at cip.sccp.en.b(Lcip/sccp/ay;)V(Unknown Source)
	at cip.sccp.bv.a(Lcip/sccp/ay;)V(Unknown Source)
	at cip.sccp.ay.a()Lcip/sccp/bv;(Unknown Source)
	at cip.sccp.co.e()V(Unknown Source)
	at cip.sys.l.run()V(Unknown Source)
	at java.lang.Thread.startup(Z)V(Unknown Source)
1298: WRN 08:45:04.018913 JVM: Startup Module Loader|cip.sccp.SccpEnhancedAlarmInfo:propertyChanged - name=device.settings.fullyregistered value=false
1299: WRN 08:45:04.021448 JVM: Startup Module Loader|cip.sccp.SccpEnhancedAlarmInfo:propertyChanged - name=device.status.lastresetcause2 value=465
1300: WRN 08:45:04.023042 JVM: Startup Module Loader|cip.sccp.SccpEnhancedAlarmInfo:setLastDeregistrationReason - new reason=LastTimeTCPclosed current=
1301: WRN 08:45:04.024664 JVM: Startup Module Loader|cip.sccp.CcApi:? - alarm sending failure:14: Name=SEP2C3ECF76C81E Load= 9.4(2SR1.1S) Last=UCM-closed-TCP
1302: WRN 08:45:04.049078 JVM: Startup Module Loader|cip.sccp.CcApi:? - CcAPI, LAST_RESET_CAUSE changed to 465
```
Device starts looping over and over again from this moment. I guess because the open channel was not handled correctly.
```
1303: NOT 08:45:04.066250 JVM: Startup Module Loader|cip.sccp.c:? - CcApi.statusChanged()=> 
resetState=NO_RESET
registrationState=PAUSE
isSoftResetPending=false
isDualStackResetPending=false
isRegistrationStopped=false
dhcpOption=0(DHCP_FAST)
deadIpStack=-1
1304: NOT 08:45:04.067994 JVM: Startup Module Loader|cip.sccp.df:? - SccpListener.statusChanged()=> 
resetState=NO_RESET
registrationState=PAUSE
isSoftResetPending=false
isDualStackResetPending=false
isRegistrationStopped=false
dhcpOption=0(DHCP_FAST)
deadIpStack=-1
restartRequested=false
resetRequested=false
shuttingDown=false
1305: NOT 08:45:04.070542 JVM: Startup Module Loader|cip.sccp.c:? - CcApi.statusChanged()=> 
resetState=NO_RESET
registrationState=NORMAL
isSoftResetPending=false
isDualStackResetPending=false
isRegistrationStopped=false
dhcpOption=0(DHCP_FAST)
deadIpStack=-1
1306: NOT 08:45:04.072288 JVM: Startup Module Loader|cip.sccp.df:? - SccpListener.statusChanged()=> 
resetState=NO_RESET
registrationState=NORMAL
isSoftResetPending=false
isDualStackResetPending=false
isRegistrationStopped=false
dhcpOption=0(DHCP_FAST)
deadIpStack=-1
restartRequested=false
resetRequested=false
shuttingDown=false
1307: NOT 08:45:04.132306 JVM: Startup Module Loader|cip.midp.midletsuite.InstallerModule:? - propertyChanged - device.settings.fullyregistered value=false
1308: NOT 08:45:04.134232 JVM: Startup Module Loader|cip.midp.pushregistry.e:? - setAcceptConnections - DISABLED
1309: NOT 08:45:04.136482 JVM: Startup Module Loader|cip.cfg.ConfigManager:? - --->ConfigManager PropertyChanged: device.callagent.callcount
1310: NOT 08:45:04.138368 JVM: Startup Module Loader|cip.cfg.ConfigManager:? - <---ConfigManager PropertyChanged: device.callagent.callcount
1311: NOT 08:45:04.141734 JVM: Startup Module Loader|cip.cfg.ConfigManager:? - --->ConfigManager PropertyChanged: device.callagent.callcount
1312: NOT 08:45:04.143752 JVM: Startup Module Loader|cip.cfg.ConfigManager:? - <---ConfigManager PropertyChanged: device.callagent.callcount
1313: NOT 08:45:04.146028 JVM: Startup Module Loader|cip.cfg.ConfigManager:? - --->ConfigManager PropertyChanged: device.callagent.callcount
1314: NOT 08:45:04.147868 JVM: Startup Module Loader|cip.cfg.ConfigManager:? - <---ConfigManager PropertyChanged: device.callagent.callcount
1315: WRN 08:48:04.284539 JVM: Startup Module Loader|cip.sccp.SccpEnhancedAlarmInfo:propertyChanged - name=device.settings.fullyregistered value=false
1316: NOT 08:48:04.309794 JVM: Startup Module Loader|cip.sccp.c:? - CcApi.statusChanged()=> 
resetState=RE_DHCP_REQUEST
registrationState=NORMAL
isSoftResetPending=false
isDualStackResetPending=false
isRegistrationStopped=false
dhcpOption=10(DHCP_COLDBOOT)
deadIpStack=-1
1317: NOT 08:48:04.311537 JVM: Startup Module Loader|cip.sccp.df:? - SccpListener.statusChanged()=> 
resetState=RE_DHCP_REQUEST
registrationState=NORMAL
isSoftResetPending=false
isDualStackResetPending=false
isRegistrationStopped=false
dhcpOption=10(DHCP_COLDBOOT)
deadIpStack=-1
restartRequested=false
resetRequested=false
shuttingDown=false
1318: NOT 08:48:04.313942 JVM: Startup Module Loader|cip.sccp.c:? - CcApi.statusChanged()=> 
resetState=RE_DHCP_PENDING
registrationState=STOP
isSoftResetPending=false
isDualStackResetPending=false
isRegistrationStopped=true
dhcpOption=10(DHCP_COLDBOOT)
deadIpStack=-1
1319: NOT 08:48:04.315541 JVM: Startup Module Loader|cip.sccp.c:? - CcApi doing disposeConnections ACTION
1320: NOT 08:48:04.318716 JVM: Startup Module Loader|cip.sccp.df:? - SccpListener.statusChanged()=> 
resetState=RE_DHCP_PENDING
registrationState=STOP
isSoftResetPending=false
isDualStackResetPending=false
isRegistrationStopped=true
dhcpOption=10(DHCP_COLDBOOT)
deadIpStack=-1
restartRequested=false
resetRequested=false
shuttingDown=false
1321: NOT 08:48:04.392061 JVM: Startup Module Loader|cip.midp.midletsuite.InstallerModule:? - propertyChanged - device.settings.fullyregistered value=false
1322: NOT 08:48:04.393686 JVM: Startup Module Loader|cip.midp.pushregistry.e:? - setAcceptConnections - DISABLED
1323: NOT 08:48:04.395202 JVM: Startup Module Loader|cip.cfg.ConfigManager:? - --->ConfigManager PropertyChanged: device.callagent.callcount
1324: NOT 08:48:04.396807 JVM: Startup Module Loader|cip.cfg.ConfigManager:? - <---ConfigManager PropertyChanged: device.callagent.callcount
1325: NOT 08:48:04.398384 JVM: Startup Module Loader|cip.cfg.q:? - reDhcp() IPv4=14 IPv6=-99
1326: ERR 08:48:04.404979 JVM: Startup Module Loader|cip.mmgr.MediaManager:? - 
MediaManager propertyChanged called  device.settings.network.ipstacksstate
1327: NOT 08:48:04.408012 JVM: Startup Module Loader|cip.sccp.CcApi:? - Unregister all lines due to that IP stack has gone down
1328: WRN 08:48:04.409725 JVM: Startup Module Loader|cip.sccp.SccpEnhancedAlarmInfo:propertyChanged - name=device.settings.fullyregistered value=false
1329: WRN 08:48:04.411496 JVM: Startup Module Loader|cip.sccp.SccpEnhancedAlarmInfo:propertyChanged - name=device.settings.network.ipstacksstate value=14,-99
1330: NOT 08:48:04.413330 JVM: Startup Module Loader|cip.cfg.ConfigManager:? - --->ConfigManager PropertyChanged: device.settings.network.ipstacksstate
1331: NOT 08:48:04.414888 JVM: Startup Module Loader|cip.cfg.ConfigManager:? - ConfigManager IP_STACKS_STATE changed
1332: NOT 08:48:04.416456 JVM: Startup Module Loader|cip.cfg.ConfigManager:? -   IPv4 state=SET DHCP COLDBOOT
1333: NOT 08:48:04.418062 JVM: Startup Module Loader|cip.cfg.ConfigManager:? -   IPv6 state=DHCP NOT CHANGED
1334: NOT 08:48:04.419668 JVM: Startup Module Loader|cip.cfg.ConfigManager:? - <---ConfigManager PropertyChanged: device.settings.network.ipstacksstate
1335: NOT 08:48:04.421991 JVM: Startup Module Loader|cip.cfg.ConfigManager:? - --->ConfigManager PropertyChanged: device.callagent.callcount
1336: NOT 08:48:04.423552 JVM: Startup Module Loader|cip.cfg.ConfigManager:? - <---ConfigManager PropertyChanged: device.callagent.callcount
1337: NOT 08:48:04.428536 JVM: Startup Module Loader|cip.midp.midletsuite.InstallerModule:? - propertyChanged - device.settings.fullyregistered value=false
1338: NOT 08:48:04.430155 JVM: Startup Module Loader|cip.midp.pushregistry.e:? - setAcceptConnections - DISABLED
1339: NOT 08:48:04.431480 DHCP: Restart - delay = 1 
1340: NOT 08:48:04.437421 DHCP: Sending Release... 
1341: NOT 08:48:06.445941 DHCP:  dhcpSendReq: status 0x12300000,state:2 
1342: NOT 08:48:06.446632 DHCP: Sending Request... 
1343: NOT 08:48:06.448563 DHCP: ACK received 
1344: WRN 08:48:06.449202 DHCP: dhcpValidateIP(): invalid ip 0x0
1345: WRN 08:48:06.449781 DHCP: dhcpValidateIP(): invalid ip 0x0
1346: WRN 08:48:06.450399 DHCP: dhcpValidateIP(): invalid ip 0x0
1347: WRN 08:48:06.450966 DHCP: dhcpValidateIP(): invalid ip 0x0
1348: WRN 08:48:06.451480 DHCP: dhcpValidateIP(): invalid ip 0x0
```

**Comment by dkgroot** [comment] 2016-12-14 23:11
Hi Andy,
Please update in a couple of steps through these revisions
11eb22f5, 049869, f53c1ad and edb0385

Your revision is very close to the first 3 revisions, so that should not be a problem. The last one is a little further ahead (and could contain regressions compared to your current enviroment).

I would like to make sure this issue is not already fixed, before investigating the 201 callreference / callid further.

**Comment by abradfordcms** [comment] 2016-12-14 23:12
Hi Diederik,

Sure thing - will be giving this a try.

Andy

On Wed, Dec 14, 2016 at 6:11 PM, Diederik de Groot <notifications@github.com

**Comment by dkgroot** [comment] 2016-12-14 23:22
Already checked if callInstance should have been callId, but the current source code is correct in that regard. It might have been faulty in your revision, causing the issues. Marcello must have already fixed that. Once you confirm the newer revisions, we can close this issue in this regard.

**Comment by dkgroot** [comment] 2016-12-22 11:37
@abradfordcms 
Closing this issue. Did not get any further update about it not working. If the issue is still there using the latest 'develop' branch, then please reopen the issue.

**Closed by dkgroot** 2016-12-22 11:37 UTC
Labels: branch_development, callinfo, in progress, wontfix
